name: main

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - 3.9.12
          - 3.10.4
    steps:
      - uses: actions/checkout@v2
      - run: docker build --build-arg  --tag ${{ matrix.python_version }} pyenv

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: bneijt/arch-python
          tags: |
            type=ref,event=branch
            type=raw,value=${{ matrix.python_version }},enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: pyenv
          build-args: PYTHON_VERSION=${{ matrix.python_version }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
